const API_URL = 'https://script.google.com/macros/s/AKfycbzECo_2mSZrWOjloQIPHygelRqSkwUTbymakhmSykwy0crrjaPjTvY3xXHxzChhc393Wg/exec';
const $ = (s) => document.querySelector(s);
const resourceMarkup = (items) => items.length ? items.map((r) => `<div class="resource"><span class="file-icon">▤</span><div><b title="${escapeHtml(r.name)}">${escapeHtml(r.name)}</b><small>${escapeHtml(r.meta)}</small></div><a class="download" href="${r.url}" target="_blank" rel="noopener">↓</a></div>`).join('') : '<p class="muted">No materials published yet.</p>';
const escapeHtml = (text='') => String(text).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formatBytes(bytes) { if (!bytes) return '—'; if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
async function syncFromApi() { try { const response = await fetch(`${API_URL}?t=${Date.now()}`, {cache:'no-store'}); if (!response.ok) return; const data = await response.json(); const classroom = data.classroom || {}; if (classroom.title && $('#roomTitle')) $('#roomTitle').textContent = classroom.title; if (classroom.prompt && $('#promptText')) $('#promptText').textContent = classroom.prompt; if (classroom.title && $('#promptTitle')) $('#promptTitle').textContent = classroom.title; const resources = (data.resources || []).map((file) => ({name:file.name, meta:`${file.mimeType || 'File'} · ${formatBytes(file.size)}`, url:file.url || '#'})); if ($('#resourceList')) { $('#resourceList').innerHTML = resourceMarkup(resources); $('#resourceCount').textContent = resources.length; } } catch (_) {} }
syncFromApi(); setInterval(syncFromApi, 5000);
if ($('#copyPrompt')) $('#copyPrompt').addEventListener('click', async () => { await navigator.clipboard?.writeText($('#promptText').textContent.trim()); $('#copyMessage').textContent = 'Copied — ready to paste into ChatGPT'; setTimeout(() => $('#copyMessage').textContent = '', 2800); });
if ($('[data-action="done"]')) $('[data-action="done"]').addEventListener('click', (e) => { e.currentTarget.classList.add('selected'); $('#doneCount').textContent = 'Marked as done'; });
if ($('[data-action="question"]')) $('[data-action="question"]').addEventListener('click', () => $('#questionBox').classList.toggle('hidden'));
if ($('#sendQuestion')) $('#sendQuestion').addEventListener('click', async () => { const question = $('#questionText').value.trim(); if (!question) return; try { await fetch(API_URL, {method:'POST', headers:{'Content-Type':'text/plain;charset=utf-8'}, body:JSON.stringify({action:'question', question})}); } catch (_) {} $('#questionText').value=''; $('#questionBox').classList.add('hidden'); alert('Question sent to your teacher.'); });
