const API_URL = 'https://script.google.com/macros/s/AKfycbzECo_2mSZrWOjloQIPHygelRqSkwUTbymakhmSykwy0crrjaPjTvY3xXHxzChhc393Wg/exec';
const TEACHER_KEY = '940119';
const $ = (s) => document.querySelector(s);
const escapeHtml = (text='') => String(text).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatBytes = (bytes) => !bytes ? '—' : bytes < 1048576 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1048576).toFixed(1)} MB`;
const resourceMarkup = (items) => items.length ? items.map((r) => `<div class="resource"><span class="file-icon">▤</span><div><b title="${escapeHtml(r.name)}">${escapeHtml(r.name)}</b><small>${escapeHtml(r.meta)}</small></div><a class="download" href="${r.url}" target="_blank" rel="noopener">↓</a></div>`).join('') : '<p class="muted">No materials published yet.</p>';
function openConsole() { $('#loginGate').classList.add('hidden'); $('#teacherApp').classList.remove('hidden'); syncFromApi(); }
if (sessionStorage.getItem('classroomTeacherUnlocked') === 'yes') openConsole();
$('#unlockTeacher').addEventListener('click', () => { if ($('#teacherKey').value.trim() === TEACHER_KEY) { sessionStorage.setItem('classroomTeacherUnlocked','yes'); openConsole(); } else $('#loginMessage').textContent = 'Incorrect key. Please try again.'; });
$('#teacherKey').addEventListener('keydown', (e) => { if (e.key === 'Enter') $('#unlockTeacher').click(); });
async function syncFromApi() { try { const r = await fetch(`${API_URL}?t=${Date.now()}`, {cache:'no-store'}); if (!r.ok) return; const data = await r.json(); const c = data.classroom || {}; if (c.title) { $('#roomTitle').textContent = c.title; $('#teacherPromptTitle').value = c.title; } if (c.prompt) $('#teacherPrompt').value = c.prompt; const files = (data.resources || []).map((f) => ({name:f.name, meta:`${f.mimeType || 'File'} · ${formatBytes(f.size)}`, url:f.url || '#'})); $('#teacherResourceList').innerHTML = resourceMarkup(files); $('#teacherResourceCount').textContent = files.length; } catch (_) {} }
setInterval(() => { if (!$('#teacherApp').classList.contains('hidden')) syncFromApi(); }, 5000);
$('#copyStudentLink').addEventListener('click', async () => { const link = new URL('../', location.href).href; await navigator.clipboard?.writeText(link); $('#teacherMessage').textContent = `Student link copied: ${link}`; setTimeout(() => $('#teacherMessage').textContent='', 3500); });
$('#newRoom').addEventListener('click', async () => { const title = window.prompt('Room name', 'New AI Prompt Workshop'); if (title === null) return; const roomId = `ROOM-${String(Date.now()).slice(-6)}`; $('#newRoom').disabled = true; try { const r = await fetch(API_URL, {method:'POST', headers:{'Content-Type':'text/plain;charset=utf-8'}, body:JSON.stringify({action:'createRoom', roomId, title, prompt:''})}); const d = await r.json(); if (!d.ok) throw new Error(d.error); $('#teacherMessage').textContent = `Room ${roomId} is ready. Publish your first prompt.`; await syncFromApi(); } catch (_) { $('#teacherMessage').textContent = 'Could not create the room. Please try again.'; } finally { $('#newRoom').disabled = false; } });
$('#publishPrompt').addEventListener('click', async () => { const title = $('#teacherPromptTitle').value.trim() || 'Latest prompt'; const prompt = $('#teacherPrompt').value.trim(); if (!prompt) return; $('#publishPrompt').disabled = true; try { const r = await fetch(API_URL, {method:'POST', headers:{'Content-Type':'text/plain;charset=utf-8'}, body:JSON.stringify({action:'publishPrompt', title, prompt})}); const d = await r.json(); if (!d.ok) throw new Error(d.error); $('#teacherMessage').textContent = 'Prompt published to students.'; } catch (_) { $('#teacherMessage').textContent = 'Could not publish the prompt.'; } finally { $('#publishPrompt').disabled = false; } });
$('#chooseFile').addEventListener('click', () => $('#fileInput').click()); $('#dropzone').addEventListener('click', () => $('#fileInput').click()); $('#fileInput').addEventListener('change', () => { const f=$('#fileInput').files[0]; if(f){$('#resourceName').value=f.name; $('#dropzone b').textContent=f.name;} });
$('#publishFile').addEventListener('click', () => { const file=$('#fileInput').files[0]; if(!file){$('#fileInput').click(); return;} const reader=new FileReader(); reader.onload=async()=>{ const button=$('#publishFile'); button.disabled=true; button.textContent='Uploading…'; try { const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'upload',filename:$('#resourceName').value.trim()||file.name,mimeType:file.type,base64:String(reader.result).split(',')[1]})}); const d=await r.json(); if(!d.ok) throw new Error(d.error); $('#teacherMessage').textContent='File uploaded and published.'; await syncFromApi(); } catch (_) { $('#teacherMessage').textContent='Upload failed. Please try again.'; } finally { button.disabled=false; button.textContent='Upload and publish'; $('#resourceName').value=''; $('#fileInput').value=''; $('#dropzone b').textContent='Drop a file here'; } }; reader.readAsDataURL(file); });
