const API_URL='https://script.google.com/macros/s/AKfycbzECo_2mSZrWOjloQIPHygelRqSkwUTbymakhmSykwy0crrjaPjTvY3xXHxzChhc393Wg/exec';
const TEACHER_KEY='940119'; const $=s=>document.querySelector(s);
const esc=t=>String(t||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=b=>!b?'—':b<1048576?Math.max(1,Math.round(b/1024))+' KB':(b/1048576).toFixed(1)+' MB';
const markup=a=>a.length?a.map(r=>'<div class="resource"><span class="file-icon">▤</span><div><b>'+esc(r.name)+'</b><small>'+esc(r.meta)+'</small></div><a class="download" href="'+r.url+'" target="_blank" rel="noopener">↓</a></div>').join(''):'<p class="muted">No materials published yet.</p>';
function openConsole(){$('#loginGate').classList.add('hidden');$('#teacherApp').classList.remove('hidden');sync();}
if(sessionStorage.getItem('classroomTeacherUnlocked')==='yes')openConsole();
$('#unlockTeacher').addEventListener('click',()=>{if($('#teacherKey').value.trim()===TEACHER_KEY){sessionStorage.setItem('classroomTeacherUnlocked','yes');openConsole();}else $('#loginMessage').textContent='Incorrect key. Please try again.';});
$('#teacherKey').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockTeacher').click();});
async function sync(){try{const r=await fetch(API_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json(),c=d.classroom||{};if(c.title){$('#roomTitle').textContent=c.title;$('#teacherPromptTitle').value=c.title;}if(c.prompt)$('#teacherPrompt').value=c.prompt;const f=(d.resources||[]).map(x=>({name:x.name,meta:(x.mimeType||'File')+' · '+bytes(x.size),url:x.url||'#'}));$('#teacherResourceList').innerHTML=markup(f);$('#teacherResourceCount').textContent=f.length;}catch(e){}}
setInterval(()=>{if(!$('#teacherApp').classList.contains('hidden'))sync();},5000);
$('#copyStudentLink').addEventListener('click',async()=>{const l=location.origin+'/classroom-link/';await navigator.clipboard?.writeText(l);$('#teacherMessage').textContent='Student link copied: '+l;setTimeout(()=>$('#teacherMessage').textContent='',3500);});
$('#newRoom').addEventListener('click',async()=>{const title=window.prompt('Room name','New AI Prompt Workshop');if(title===null)return;const id='ROOM-'+String(Date.now()).slice(-6);$('#newRoom').disabled=true;try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'createRoom',roomId:id,title:title,prompt:''})}),d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='Room '+id+' is ready. Publish your first prompt.';await sync();}catch(e){$('#teacherMessage').textContent='Could not create the room.';}finally{$('#newRoom').disabled=false;}});
$('#publishPrompt').addEventListener('click',async()=>{const title=$('#teacherPromptTitle').value.trim()||'Latest prompt',prompt=$('#teacherPrompt').value.trim();if(!prompt)return;$('#publishPrompt').disabled=true;try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'publishPrompt',title:title,prompt:prompt})}),d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='Prompt published to students.';}catch(e){$('#teacherMessage').textContent='Could not publish the prompt.';}finally{$('#publishPrompt').disabled=false;}});
$('#chooseFile').addEventListener('click',()=>$('#fileInput').click());$('#dropzone').addEventListener('click',()=>$('#fileInput').click());$('#fileInput').addEventListener('change',()=>{const f=$('#fileInput').files[0];if(f){$('#resourceName').value=f.name;$('#dropzone b').textContent=f.name;}});
$('#publishFile').addEventListener('click',()=>{const f=$('#fileInput').files[0];if(!f){$('#fileInput').click();return;}const rd=new FileReader();rd.onload=async()=>{const b=$('#publishFile');b.disabled=true;b.textContent='Uploading…';try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'upload',filename:$('#resourceName').value.trim()||f.name,mimeType:f.type,base64:String(rd.result).split(',')[1]})}),d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='File uploaded and published.';await sync();}catch(e){$('#teacherMessage').textContent='Upload failed. Please try again.';}finally{b.disabled=false;b.textContent='Upload and publish';$('#resourceName').value='';$('#fileInput').value='';$('#dropzone b').textContent='Drop a file here';}};rd.readAsDataURL(f);});
