const API_URL='https://script.google.com/macros/s/AKfycbywLNmsr1QDsYWlSgoA6AZ79b8crQrfSkkoLGFTPLu1SkssgNy6xIEfdKS_Q_B8wRBFYQ/exec';
const TEACHER_KEY='940119'; const $=s=>document.querySelector(s); let currentRoomId=''; let currentRoomPassword='';
const esc=t=>String(t||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const bytes=b=>!b?'—':b<1048576?Math.max(1,Math.round(b/1024))+' KB':(b/1048576).toFixed(1)+' MB'; const markup=a=>a.length?a.map(r=>'<div class="resource"><span class="file-icon">▤</span><div><b>'+esc(r.name)+'</b><small>'+esc(r.meta)+'</small></div><a class="download" href="'+r.url+'" target="_blank" rel="noopener">↓</a></div>').join(''):'<p class="muted">No materials published yet.</p>';
function openConsole(){ $('#loginGate').classList.add('hidden'); $('#teacherApp').classList.remove('hidden'); listRooms(); } if(sessionStorage.getItem('classroomTeacherUnlocked')==='yes')openConsole();
$('#unlockTeacher').addEventListener('click',()=>{if($('#teacherKey').value.trim()===TEACHER_KEY){sessionStorage.setItem('classroomTeacherUnlocked','yes');openConsole();}else $('#loginMessage').textContent='Incorrect key. Please try again.';}); $('#teacherKey').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockTeacher').click();});
async function apiGet(action,extra={}){const q=new URLSearchParams({action,teacherKey:TEACHER_KEY,...extra});const r=await fetch(API_URL+'?'+q.toString(),{cache:'no-store'});return r.json();}
async function listRooms(){try{const d=await apiGet('listRooms');const select=$('#roomSelect');select.innerHTML='';(d.rooms||[]).forEach(r=>{const o=document.createElement('option');o.value=r.roomId;o.textContent=r.roomId+' · '+r.title+' ('+r.status+')';select.appendChild(o);});if(d.rooms&&d.rooms.length)await loadRoom(d.rooms[0].roomId);}catch(e){$('#roomSelect').innerHTML='<option>Unable to load rooms</option>';}}
async function loadRoom(id){if(!id)return;try{const d=await apiGet('teacherRoom',{roomId:id});if(!d.ok)throw Error();currentRoomId=id;currentRoomPassword=d.classroom.joinPassword||'';$('#roomSelect').value=id;$('#newRoomPassword').value=currentRoomPassword;$('#roomTitle').textContent=d.classroom.title;$('#teacherPromptTitle').value=d.classroom.title;$('#teacherPrompt').value=d.classroom.prompt||'';const files=(d.resources||[]).map(f=>({name:f.name,meta:(f.mimeType||'File')+' · '+bytes(f.size),url:f.url||'#'}));$('#teacherResourceList').innerHTML=markup(files);$('#teacherResourceCount').textContent=files.length;}catch(e){$('#teacherMessage').textContent='Could not load this room.';}}
$('#loadRoom').addEventListener('click',()=>loadRoom($('#roomSelect').value)); $('#roomSelect').addEventListener('change',()=>loadRoom($('#roomSelect').value));
$('#copyStudentLink').addEventListener('click',async()=>{const link=location.origin+'/classroom-link/?room='+encodeURIComponent(currentRoomId);await navigator.clipboard?.writeText(link);$('#teacherMessage').textContent='Student link copied: '+link;setTimeout(()=>$('#teacherMessage').textContent='',3500);});
$('#newRoom').addEventListener('click',async()=>{const title=window.prompt('Room name','New AI Prompt Workshop');if(title===null)return;const password=window.prompt('Password for students','');if(!password)return;$('#newRoom').disabled=true;try{const id='ROOM-'+String(Date.now()).slice(-6);const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'createRoom',teacherKey:TEACHER_KEY,roomId:id,title:title,password:password})});const d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='Room created. Select it and copy the student link.';await listRooms();}catch(e){$('#teacherMessage').textContent='Could not create the room.';}finally{$('#newRoom').disabled=false;}});
$('#publishPrompt').addEventListener('click',async()=>{if(!currentRoomId)return;const title=$('#teacherPromptTitle').value.trim()||'Latest prompt',prompt=$('#teacherPrompt').value.trim();try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'publishPrompt',teacherKey:TEACHER_KEY,roomId:currentRoomId,title,prompt})});const d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='Prompt published to this room.';}catch(e){$('#teacherMessage').textContent='Could not publish the prompt.';}});
$('#chooseFile').addEventListener('click',()=>$('#fileInput').click()); $('#dropzone').addEventListener('click',()=>$('#fileInput').click()); $('#fileInput').addEventListener('change',()=>{const f=$('#fileInput').files[0];if(f){$('#resourceName').value=f.name;$('#dropzone b').textContent=f.name;}});
$('#publishFile').addEventListener('click',()=>{const f=$('#fileInput').files[0];if(!f||!currentRoomId){$('#teacherMessage').textContent='Choose a room and a file first.';return;}const rd=new FileReader();rd.onload=async()=>{const b=$('#publishFile');b.disabled=true;b.textContent='Uploading…';try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'upload',teacherKey:TEACHER_KEY,roomId:currentRoomId,filename:$('#resourceName').value.trim()||f.name,mimeType:f.type,base64:String(rd.result).split(',')[1]})});const d=await r.json();if(!d.ok)throw Error();$('#teacherMessage').textContent='File uploaded and published.';await loadRoom(currentRoomId);}catch(e){$('#teacherMessage').textContent='Upload failed.';}finally{b.disabled=false;b.textContent='Upload and publish';$('#resourceName').value='';$('#fileInput').value='';$('#dropzone b').textContent='Drop a file here';}};rd.readAsDataURL(f);});
